# Generated by Django 5.2 on 2025-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
